- id: '1664448986931'
  alias: 3AM coffe for Will Mon-Thurs
  description: ''
  trigger:
  - platform: time
    at: 02:48:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    before: 00:00:00
    after: 00:00:00
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.coffee_cord
  mode: single
