homeassistant:
    latitude: 42.5881126
    longitude: -74.3309562
    elevation: 230
    unit_system: imperial
    time_zone: America/New_York
    customize: !include_dir_merge_named customize/
    auth_providers:
        - type: homeassistant
        - type: legacy_api_password
          api_password: !secret http_password
        - type: trusted_networks
          trusted_networks:
              - 192.168.1.0/24
              - 192.168.2.0/24
              - 192.168.3.0/24

frontend:
    themes: !include_dir_merge_named themes/

lovelace:
    mode: yaml

    resources:
      - url: /local/custom-lovelace/weather-card/weather-card.js
        type: module
      - url: /local/custom-lovelace/mini-media-player/mini-media-player-bundle.js?v=1.4.2
        type: module
      - url: /local/custom-lovelace/simple-thermostat/simple-thermostat.js?v=1
        type: module
      - url: /local/custom-lovelace/mini-graph-card/mini-graph-card-bundle.js?v=0.8.2
        type: module
      - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.2
        type: js
      - url: /local/custom-lovelace/text-element/text-element.js?v=0
        type: js

# HTTP options
http:
    cors_allowed_origins:
        - https://google.com
        - https://www.home-assistant.io
    use_x_forwarded_for: true
    trusted_proxies:
        - 127.0.0.1
        - ::1
        - 192.168.3.10
    ip_ban_enabled: True
    login_attempts_threshold: 5

# Config options
config:

# HassIO options
hassio:

#System Health Monitor
system_health:

# Checks for available updates
updater:

# Discover some devices automatically
#discovery: false

# Set up recorder information
recorder:
    db_url: !secret database_url
    include:
        domains:
          - sensor
          - binary_sensor
          - person
    exclude:
        entities:
          - sensor.last_boot
          - sensor.date

# Enables support for tracking state changes over time.
history:
    include:
        domains:
          - sensor
          - binary_sensor
          - person
    exclude:
        entities:
          - sensor.last_boot
          - sensor.date

# View all events in a logbook
logbook:
    include:
        domains:
          - sensor
          - switch
          - binary_sensor
          - device_tracker
          - person
    exclude:
        entities:
          - sensor.last_boot
          - sensor.date

#Enables Sun component
sun:

# Automations
automation: !include_dir_merge_list automations/
#Scripts
script: !include_dir_merge_named scripts/
rest_command: !include components/rest_command.yaml
# Components
binary_sensor: !include components/binary_sensor.yaml
input_boolean: !include components/input_boolean.yaml
camera: !include components/camera.yaml
person: !include components/persons.yaml
google_assistant: !include components/google_assistant.yaml
device_tracker: !include components/device_tracker.yaml
android_ip_webcam: !include components/android_ip_webcam.yaml
ombi: !include components/ombi.yaml
apcupsd: !include components/apcupsd.yaml
notify: !include components/notify.yaml
sensor: !include components/sensor.yaml
switch: !include components/switch.yaml
light: !include components/light.yaml
weather: !include components/weather.yaml
input_number: !include components/input_number.yaml
input_select: !include components/input_select.yaml
zone: !include components/zones.yaml

# Groups and Views
# group: !include groups.yaml
