# Main HA settings
homeassistant:
    auth_providers:
        - type: homeassistant
        - type: trusted_networks
          trusted_networks:
              - 192.168.0.0/16

# Themes only atm
frontend:
    themes: !include_dir_merge_named themes/

# UI Resources
lovelace:
    mode: yaml
    resources:
    #Modules
      - url: /local/community/mini-media-player/mini-media-player-bundle.js
        type: module
      - url: /local/community/simple-thermostat/simple-thermostat.js
        type: module
      - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
        type: module
      - url: /local/community/apexcharts-card/apexcharts-card.js
        type: module
      - url: /local/community/lovelace-mushroom/mushroom.js
        type: module
      - url: /local/community/restriction-card/restriction-card.js
        type: module
      - url: /local/community/kb-steam-card/kb-steam-card.js
        type: module
      - url: /local/community/button-card/button-card.js
        type: module
      - url: /local/community/bar-card/bar-card.js
        type: module
      - url: /local/community/weather-radar-card/weather-radar-card.js
        type: module
      - url: /local/community/ha-teamtracker-card/ha-teamtracker-card.js
        type: module
      - url: /local/community/lovelace-hourly-weather/hourly-weather.js
        type: module
    #Javascript
      - url: /local/custom-lovelace/text-element/text-element.js?v=0
        type: js

# HTTP options
http:
    cors_allowed_origins:
        - https://google.com
        - https://www.home-assistant.io
    use_x_forwarded_for: true
    trusted_proxies:
        - 127.0.0.1
        - ::1
        - 192.168.3.10
    ip_ban_enabled: True
    login_attempts_threshold: 5

# Config options
config:

# HassIO options
hassio:

#System Health Monitor
system_health:

# Discover some devices automatically
#discovery: false

# Set up recorder information
recorder:
    db_url: !secret database_url

# View all events in a logbook
logbook:

logger:
  default: info

#Enables Sun component
sun:

# Custom sidebar
panel_custom: !include components/panel_custom.yaml
# Automations
automation: !include_dir_merge_list automations/
# Scripts
script: !include_dir_merge_named scripts/
shell_command: !include components/shell_command.yaml
# Persons
person: !include components/persons.yaml
# Components
binary_sensor: !include components/binary_sensor.yaml
camera: !include components/camera.yaml
google_assistant: !include components/google_assistant.yaml
sensor: !include components/sensor.yaml
switch: !include components/switch.yaml
light: !include components/light.yaml
notify: !include components/notify.yaml