custom_header:
    compact_mode: true
    menu_hide: true
    hide_config: true
    hide_raw: true
    hide_help: true
    options_hide: true
resources:
  - url: /local/custom-lovelace/custom-header/custom-header.js?v=0.0.1
    type: module
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
  - url: /local/custom-lovelace/mini-media-player/mini-media-player-bundle.js?v=1.4.2
    type: module
  - url: /local/custom-lovelace/simple-thermostat/simple-thermostat.js?v=1
    type: module
  - url: /local/custom-lovelace/mini-graph-card/mini-graph-card-bundle.js?v=0.8.2
    type: module
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.2
    type: js
  - url: /local/custom-lovelace/text-element/text-element.js?v=0
    type: js

views:
################################################################################
# Home tab
################################################################################
  - title: Home
    icon: mdi:home
    path: home
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            name: Will
            entity: person.will
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/will_home.png
                "not_home": /local/images/avatars/will_not_home.png
                "Wills Work": /local/images/avatars/will_work.png
                "Mom and Dads": /local/images/avatars/will_mnd.png
                "unknown": /local/images/avatars/will_not_home.png

          - type: picture-entity
            name: Melissa
            entity: person.melissa
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/melissa_home.png
                "not_home": /local/images/avatars/melissa_not_home.png
                "unknown": /local/images/avatars/melissa_not_home.png

          - type: picture-entity
            name: Jacob
            entity: person.jacob
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/jacob_home.png
                "not_home": /local/images/avatars/jacob_not_home.png
                "unknown": /local/images/avatars/jacob_not_home.png

          - type: picture-entity
            name: Kaleb
            entity: person.kaleb
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/kaleb_home.png
                "not_home": /local/images/avatars/kaleb_not_home.png
                "unknown": /local/images/avatars/kaleb_not_home.png

      - type: glance
        show_state: false
        columns: 3
        entities:
          - entity: light.desk_lamp
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: light.bedside_lamps
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.coffee_maker
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.greyskull
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.brotherprinter
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.consoles
            tap_action:
                action: toggle
            hold_action:
                action: more-info

      - type: custom:mini-media-player
        entity: media_player.roku_ultra
        hide:
            power: true
            source: true
            volume: true
        shortcuts:
            columns: 3
            buttons:
              - icon: mdi:plex
                type: source
                id: Plex - Stream Free TV & Movies
              - icon: mdi:netflix
                type: source
                id: Netflix
              - icon: mdi:home
                type: source
                id: Home

      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/custom-lovelace/weather-card/icons/'

      - type: custom:simple-thermostat
        entity: climate.stelpro_stzw402_electronic_thermostat_mode
        step_size: 1
        control:
            preset: false
            Heat Econ: false
        sensors:
          - entity: sensor.livingroomtemp
            name: Front Door
          - entity: sensor.stelpro_stzw402_electronic_thermostat_temperature_2
            name: Living Room
          - entity: sensor.vision_zp3102_pir_motion_sensor_temperature
            name: Kitchen

      - type: picture-glance
        entities:
          - binary_sensor.front_porch_motion
#          - binary_sensor.perimeter_kitchenmotion
          - binary_sensor.perimeter_frontdoor
#          - binary_sensor.perimeter_heavydoor
          - binary_sensor.perimeter_garagereardoor
          - binary_sensor.perimeter_garagedoor
          - switch.garagedooropener
        camera_image: camera.front_porch

      - type: entities
        show_header_toggle: false
        entities:
          - sensor.melissas_miles
          - sensor.wills_miles

      - type: custom:mini-graph-card
        line_width: 5
        hours_to_show: 48
        points_per_hour: 0.25
        animate: false
        show:
            fill: false
            labels: hover
            name_adaptive_color: true
        entities:
          - entity: sensor.stelpro_stzw402_electronic_thermostat_temperature_2
            name: Living Room
          - entity: sensor.livingroomtemp
            name: Front Door
          - entity: sensor.vision_zp3102_pir_motion_sensor_temperature
            name: Kitchen
          - entity: sensor.vision_security_zp3111_multisensor_4in1_temperature
            name: Basement
          - entity: sensor.vision_security_zp3111_multisensor_4in1_temperature_3
            name: Attic

################################################################################
# Server tab
################################################################################
  - title: Power & Stats
    icon: mdi:dip-switch
    path: server
    cards:
      - type: custom:mini-graph-card
        line_width: 5
        hours_to_show: 24
        points_per_hour: 1
        animate: false
        show:
            graph: bar
            fill: false
            labels: hover
        entities:
          - sensor.serverrack

      - type: horizontal-stack
        cards:
          - type: gauge
            name: CPU Load
            unit: '%'
            entity: sensor.kennel_intel_core_i5_4690_load_cpu_total
            severity:
                green: 0
                yellow: 45
                red: 85

          - type: gauge
            name: Memory Load
            unit: '%'
            entity: sensor.kennel_generic_memory_load_memory
            severity:
                green: 0
                yellow: 45
                red: 85

      - type: horizontal-stack
        cards:
          - type: gauge
            name: Boot Drive Usage
            unit: '%'
            entity: sensor.kennel_wdc_wd1003fbyz_010fb0_load_used_space
            severity:
                green: 0
                yellow: 45
                red: 85

          - type: gauge
            name: Storage Array Usage
            unit: '%'
            entity: sensor.kennel_generic_hard_disk_load_used_space
            severity:
                green: 0
                yellow: 45
                red: 85

      - type: entities
        entities:
          - sensor.serverrack
          - sensor.kennel_intel_core_i5_4690_temperatures_cpu_package
          - sensor.kennel_generic_memory_data_available_memory
          - sensor.kennel_generic_memory_data_used_memory

      - type: horizontal-stack
        cards:
          - type: glance
            title: HDD Temps
            entities:
              - sensor.kennel_wdc_wd1003fbyz_010fb0_temperatures_temperature
              - sensor.kennel_st3000vn000_1h4167_temperatures_temperature
              - sensor.kennel_st3000vn000_1h4167_temperatures_temperature_2
              - sensor.kennel_st3000vn000_1h4167_temperatures_temperature_3
              - sensor.kennel_st3000vn000_1hj166_temperatures_temperature
              - sensor.kennel_st3000vn000_1hj166_temperatures_temperature_2

################################################################################
# Power tab
################################################################################
  - title: Power
    icon: mdi:power-socket-us
    path: power
    cards:
      - type: custom:mini-graph-card
        line_width: 5
        hours_to_show: 24
        animate: false
        show:
            fill: false
            labels: hover
            name_adaptive_color: true
        entities:
          - sensor.deskcomputer
          - sensor.livingroomtv
          - sensor.kidstv
          - sensor.consoles

      - type: entities
        entities:
          - sensor.deskcomputer
          - sensor.livingroomtv
          - sensor.consoles
          - sensor.kidstv

      - type: horizontal-stack
        cards:
          - type: picture-entity
            name: Washing Machine
            entity: binary_sensor.perimeter_washingmachine
            show_state: false
            state_image:
                "on": /local/images/washer_on.png
                "off": /local/images/washer_off.png

          - type: picture-entity
            name: Clothes Dryer
            entity: binary_sensor.perimeter_clothesdryer
            show_state: false
            state_image:
                "on": /local/images/dryer_on.png
                "off": /local/images/dryer_off.png

      - type: horizontal-stack
        cards:
          - type: gauge
            name: Kitchen Sensor
            unit: '%'
            entity: sensor.zwave_kitchenmotion_battery

          - type: gauge
            name: Sliding Door Sensor
            unit: '%'
            entity: sensor.zwave_heavydoor_battery

      - type: horizontal-stack
        cards:
          - type: gauge
            name: Attic 4in1 Sensor
            unit: '%'
            entity: sensor.zwave_attic4in1_battery

          - type: gauge
            name: Basement 4in1 Sensor
            unit: '%'
            entity: sensor.zwave_basement4in1_battery

      - type: horizontal-stack
        cards:
          - type: gauge
            name: Dryer Sensor
            unit: '%'
            entity: sensor.zwave_shocksensor_clothesdryer_battery

          - type: gauge
            name: Washer Sensor
            unit: '%'
            entity: sensor.zwave_shocksensor_washingmachine_battery


################################################################################
# Map tab
################################################################################

  - title: Map
    icon: mdi:google-maps
    path: map
    panel: true
    cards:
      - type: map
        entities:
          - zone.home
          - zone.wills_work
          - zone.mom_and_dads
          - zone.gram_and_pas
          - zone.fred_boys
          - person.will

################################################################################
# Media tab
################################################################################
  - title: Media
    icon: mdi:movie-roll
    path: media
    cards:

      - type: picture-elements
        image: /local/images/plex_banner.jpg
        elements:
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Total </b>"
            style: {left: 20%, top: 14%}
          - type: state-label
            entity: sensor.tautulli
            style: {color: white, font-size: 16px, left: 20%, top: 26%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Direct play </b>"
            style: {left: 55%, top: 14%}
          - type: state-label
            # prefix: 'Direct play: '
            entity: sensor.tautulli_direct_plays
            style: {color: white, font-size: 16px, left: 55%, top: 26%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Direct stream </b>"
            style: {left: 20%, top: 44%}
          - type: state-label
            entity: sensor.tautulli_direct_streams
            style: {color: white, font-size: 16px, left: 20%, top: 56%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Transcode </b>"
            style: {text-align: left,left: 55%, top: 44%}
          - type: state-label
            entity: sensor.tautulli_count_transcode
            style: {color: white, font-size: 16px, left: 55%, top: 56%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>LAN bandwidth </b>"
            style: {left: 20%, top: 74%}
          - type: state-label
            entity: sensor.tautulli_lan_bandwidth
            style: {color: white, font-size: 16px, left: 20%, top: 86%}

          - type: custom:text-element
            text: "<b text-align: left, style='color: orange; font-size: 16px'>WAN bandwidth </b>"
            style: {left: 55%, top: 74%}
          - type: state-label
            entity: sensor.tautulli_wan_bandwidth
            style: {color: white, font-size: 16px, left: 55%, top: 86%}

      - type: entities
        title: TV Stats
        show_header_toggle: false
        entities:
          - sensor.sonarr_series
          - sensor.sonarr_upcoming

      - type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
        image_style: poster

      - type: entities
        title: Movie Stats
        show_header_toggle: false
        entities:
          - sensor.radarr_movies
          - sensor.radarr_upcoming

      - type: custom:upcoming-media-card
        entity: sensor.radarr_upcoming_media
        image_style: poster


################################################################################
# Misc tab
################################################################################
  - title: Misc
    icon: mdi:clipboard-pulse
    path: misc
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - entity: switch.automatic_coffee
            name: Automatic Coffee
          - entity: switch.friday_coffee
            name: Overtime Coffee

      - type: custom:mini-graph-card
        line_width: 5
        hours_to_show: 48
        points_per_hour: 0.25
        animate: false
        show:
            fill: false
            labels: hover
        entities:
          - entity: sensor.vision_security_zp3111_multisensor_4in1_relative_humidity
            name: Basement
          - entity: sensor.vision_security_zp3111_multisensor_4in1_relative_humidity_3
            name: Attic

      - type: glance
        title: SSL Expirations
        columns: 3
        entities:
          - sensor.bakkoda_com
          - sensor.unifi_video
          - sensor.librenms
          - sensor.kanboard
          - sensor.hassio
          - sensor.scary_leg_runners

      - type: entities
        title: Server Update Stats
        show_header_toggle: false
        entities:
          - sensor.ansible_status
          - sensor.pihole_status
          - sensor.database_backups
          - sensor.personal_backups
          - sensor.servers_backups
          - sensor.critical_backups
          - sensor.weekly_backups

      - type: entities
        title: Pi-Hole Stats
        show_header_toggle: false
        entities:
          - sensor.pi_hole_domains_blocked
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_ads_percentage_blocked_today
