resources:
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module

title: The Doghouse
views:
################################################################################
# Home tab
################################################################################
  - title: Home
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            name: Will
            entity: person.will
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/will_home.png
                "not_home": /local/images/avatars/will_not_home.png
                "Wills Work": /local/images/avatars/will_work.png
                "unknown": /local/images/avatars/will_not_home.png

          - type: picture-entity
            name: Melissa
            entity: person.melissa
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/melissa_home.png
                "not_home": /local/images/avatars/melissa_not_home.png
                "unknown": /local/images/avatars/melissa_not_home.png

          - type: picture-entity
            name: Jacob
            entity: person.jacob
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/jacob_home.png
                "not_home": /local/images/avatars/jacob_not_home.png
                "unknown": /local/images/avatars/jacob_not_home.png

          - type: picture-entity
            name: Kaleb
            entity: person.kaleb
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/kaleb_home.png
                "not_home": /local/images/avatars/kaleb_not_home.png
                "unknown": /local/images/avatars/kaleb_not_home.png

      - type: glance
        show_state: false
        columns: 3
        entities:
          - entity: light.desk_lamp
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: light.bedside_lamps
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.coffee_maker
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.greyskull
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.brotherprinter
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.consoles
            tap_action:
                action: toggle
            hold_action:
                action: more-info

      - type: conditional
        conditions:
          - entity: media_player.roku_ultra
            state_not: "idle"
        card:
            type: media-control
            entity: media_player.roku_ultra

      - type: entities
        show_header_toggle: false
        entities:
          - sensor.melissas_miles
          - sensor.wills_miles

      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/custom-lovelace/weather-card/icons/'

      - type: thermostat
        entity: climate.stelpro_stzw402_electronic_thermostat_heating_1

      - type: entities
        title: Temperatures
        show_header_toggle: false
        entities:
          - sensor.livingroomtemp
          - sensor.stelpro_stzw402_electronic_thermostat_temperature_2
          - sensor.vision_zp3102_pir_motion_sensor_temperature
          - entity: sensor.vision_security_zp3111_multisensor_4in1_temperature
            name: Basement
          - entity: sensor.vision_security_zp3111_multisensor_4in1_temperature_3
            name: Attic

      - type: picture-glance
        entities:
          - binary_sensor.front_porch_motion
          - binary_sensor.perimeter_kitchenmotion
          - binary_sensor.perimeter_frontdoor
          - binary_sensor.perimeter_slidingdoor
          - binary_sensor.perimeter_garagereardoor
          - binary_sensor.perimeter_garagedoor
          - switch.garagedooropener
        camera_image: camera.front_porch

#      - type: horizontal-stack
#        cards:
#          - type: picture-entity
#            name: Washing Machine
#            entity: binary_sensor.perimeter_washingmachine
#            show_state: false
#            state_image:
#                "on": /local/images/washer_on.png
#                "off": /local/images/washer_off.png
#
#          - type: picture-entity
#            name: Clothes Dryer
#            entity: binary_sensor.perimeter_clothesdryer
#            show_state: false
#            state_image:
#                "on": /local/images/dryer_on.png
#                "off": /local/images/dryer_off.png

################################################################################
# Power tab
################################################################################
  - title: Power
    icon: mdi:dip-switch
    cards:
      - type: history-graph
        title: Large Appliances
        hours_to_show: 12
        entities:
          - sensor.deskcomputer
          - sensor.livingroomtv
          - sensor.kidstv
          - sensor.consoles

      - type: entities
        entities:
          - sensor.deskcomputer
          - sensor.livingroomtv
          - sensor.consoles
          - sensor.kidstv

################################################################################
# Server tab
################################################################################
  - title: Server
    icon: mdi:server
    cards:
      - type: markdown
        content: >
            ## The Kennel Stats

      - type: history-graph
        hours_to_show: 12
        entities:
          - sensor.serverrack

      - type: horizontal-stack
        cards:
          - type: gauge
            name: CPU Load
            unit: '%'
            entity: sensor.kennel_intel_core_i5_4690_load_cpu_total
            severity:
                green: 0
                yellow: 45
                red: 85

          - type: gauge
            name: Memory Load
            unit: '%'
            entity: sensor.kennel_generic_memory_load_memory
            severity:
                green: 0
                yellow: 45
                red: 85

      - type: horizontal-stack
        cards:
          - type: gauge
            name: Boot Drive Usage
            unit: '%'
            entity: sensor.kennel_wdc_wd1003fbyz_010fb0_load_used_space
            severity:
                green: 0
                yellow: 45
                red: 85

          - type: gauge
            name: Storage Array Usage
            unit: '%'
            entity: sensor.kennel_generic_hard_disk_load_used_space
            severity:
                green: 0
                yellow: 45
                red: 85

      - type: entities
        entities:
          - sensor.serverrack
          - sensor.kennel_intel_core_i5_4690_temperatures_cpu_package
          - sensor.kennel_generic_memory_data_available_memory
          - sensor.kennel_generic_memory_data_used_memory
          - sensor.kennel_wdc_wd1003fbyz_010fb0_temperatures_temperature
          - sensor.kennel_st3000vn000_1h4167_temperatures_temperature
          - sensor.kennel_st3000vn000_1h4167_temperatures_temperature_2
          - sensor.kennel_st3000vn000_1h4167_temperatures_temperature_3
          - sensor.kennel_st3000vn000_1hj166_temperatures_temperature
          - sensor.kennel_st3000vn000_1hj166_temperatures_temperature_2

################################################################################
# Map tab
################################################################################

  - title: Map
    icon: mdi:google-maps
    panel: true
    cards:
      - type: map
        entities:
          - zone.home
          - zone.wills_work
          - zone.mom_and_dads
          - zone.gram_and_pas
          - zone.fred_boys
          - person.will

################################################################################
# Misc tab
################################################################################
  - title: Misc
    icon: mdi:clipboard-pulse
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - entity: switch.heat_saver
            name: Heat Saver (Turns back on in 1 day)
          - entity: switch.automatic_coffee
            name: Automatic Coffee
          - entity: switch.friday_coffee
            name: Overtime Coffee

      - type: entities
        title: Humidity
        show_header_toggle: false
        entities:
          - entity: sensor.vision_security_zp3111_multisensor_4in1_relative_humidity
            name: Basement
          - entity: sensor.vision_security_zp3111_multisensor_4in1_relative_humidity_3
            name: Attic

      - type: horizontal-stack
        cards:
          - type: gauge
            name: Kitchen Sensor
            unit: '%'
            entity: sensor.zwave_kitchenmotion_battery

          - type: gauge
            name: Sliding Door Sensor
            unit: '%'
            entity: sensor.zwave_slidingdoor_battery

      - type: horizontal-stack
        cards:
          - type: gauge
            name: Dryer Sensor
            unit: '%'
            entity: sensor.zwave_shocksensor_clothesdryer_battery

          - type: gauge
            name: Washer Sensor
            unit: '%'
            entity: sensor.zwave_shocksensor_washingmachine_battery

      - type: entities
        title: Sonarr Stats
        show_header_toggle: false
        entities:
          - sensor.sonarr_series
          - sensor.sonarr_wanted
          - sensor.sonarr_upcoming

      - type: entities
        title: Radarr Stats
        show_header_toggle: false
        entities:
          - sensor.radarr_movies
          - sensor.radarr_upcoming

      - type: glance
        title: SSL Expirations
        columns: 3
        entities:
          - sensor.bakkoda_com
          - sensor.unifi_video
          - sensor.librenms
          - sensor.kanboard
          - sensor.hassio
          - sensor.scary_leg_runners

      - type: entities
        title: Server Update Stats
        show_header_toggle: false
        entities:
          - sensor.ansible_status
          - sensor.pihole_status

      - type: entities
        title: Pi-Hole Stats
        show_header_toggle: false
        entities:
          - sensor.pi_hole_domains_blocked
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_ads_percentage_blocked_today
