views:
################################################################################
# Home tab
################################################################################
  - title: Home
    icon: mdi:home
    path: home
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            name: Will
            entity: person.will
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/will_home.png
                "not_home": /local/images/avatars/will_not_home.png
                "Wills Work": /local/images/avatars/will_work.png
                "Mom and Dads": /local/images/avatars/will_mnd.png
                "unknown": /local/images/avatars/will_not_home.png

          - type: picture-entity
            name: Melissa
            entity: person.melissa
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/melissa_home.png
                "not_home": /local/images/avatars/melissa_not_home.png
                "unknown": /local/images/avatars/melissa_not_home.png

          - type: picture-entity
            name: Jacob
            entity: person.jacob
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/jacob_home.png
                "not_home": /local/images/avatars/jacob_not_home.png
                "unknown": /local/images/avatars/jacob_not_home.png

          - type: picture-entity
            name: Kaleb
            entity: person.kaleb
            show_name: false
            show_state: false
            state_image:
                "home": /local/images/avatars/kaleb_home.png
                "not_home": /local/images/avatars/kaleb_not_home.png
                "unknown": /local/images/avatars/kaleb_not_home.png

# Xmas Lights
      # - type: picture-glance
      #   title: Christmas Lights
      #   entities:
      #     - light.xmas_lights
      #   state_image:
      #     "on": /local/images/xmas_lights_on.jpg
      #     "off": /local/images/xmas_lights_off.jpg
      #   entity: light.xmas_lights
      #   tap_action:
      #           action: toggle
# End Xmas Lights

      - type: glance
        show_state: false
        columns: 3
        show_name: true
        entities:
          - entity: light.desk_lamp
            name: Desk
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: light.bedside_lamps_2
            name: Bed
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: light.front_porch_lights_2
            name: Porch
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: light.outside_garage_lights_2
            name: Garage
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: light.kidsroom_lights_2
            name: Kids Room
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: light.garage_lights_2
            name: Shelves
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.coffee_cord
            name: Coffee
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.greyskull
            name: Computer
            tap_action:
                action: toggle
            hold_action:
                action: more-info
          - entity: switch.brotherprinter
            name: Printer
            tap_action:
                action: toggle
            hold_action:
                action: more-info

      - type: custom:weather-card
        entity: weather.dark_sky
        icons: '/local/custom-lovelace/weather-card/icons/'
        details: false
        hourly_forecast: false

      - type: conditional
        conditions:
          - entity: media_player.roku_tv
            state_not: "unavailable"
        card:
            type: custom:mini-media-player
            entity: media_player.roku_tv
            source: icon
            shortcuts:
                columns: 4
                buttons:
                    - icon: mdi:home
                      type: source
                      id: Home
                    - icon: mdi:plex
                      type: source
                      id: Plex - Free Movies & TV
                    - icon: mdi:netflix
                      type: source
                      id: Netflix
                    - icon: mdi:google-chrome
                      type: source
                      id: Chromecast
            hide:
              volume: true
              volume_level: true
              source: true
              progress: true

      - type: custom:simple-thermostat
        entity: climate.living_room_thermostat
        step_size: 1
        control: false
        sensors:
          - entity: sensor.living_room_thermostat_air_temperature
            name: Living Room
          - entity: sensor.livingroomtemp
            name: Front Door

      - type: picture-glance
        entities:
          - binary_sensor.fpcam1_motion
          - binary_sensor.perimeter_frontdoor
        camera_image: camera.fpcam1_high

      - type: picture-glance
        entities:
          - binary_sensor.gcam1_motion
          - binary_sensor.perimeter_garagereardoor
          - binary_sensor.perimeter_garagedoor
          - switch.garagedooropener
        camera_image: camera.gcam1_high

      - type: entities
        show_header_toggle: false
        entities:
          - sensor.melissas_miles
          - sensor.wills_miles
          - input_select.who_miles
          - input_number.miles
          - type: call-service
            icon: mdi:send-circle
            name: Submit Miles
            action_name: Submit
            service: script.turn_on
            service_data:
                entity_id: script.mile_submission

################################################################################
# Server tab
################################################################################
  - title: Server Stats
    icon: mdi:dip-switch
    path: server
    cards:
      - type: entities
        title: Kennel Stats
        entities:
          - sensor.kennel_intel_core_i5_4690_temperatures_cpu_package
          - sensor.kennel_generic_memory_data_available_memory
          - sensor.kennel_generic_memory_data_used_memory
          - sensor.kennel_wdc_wd1003fbyz_010fb0_load_used_space
          - sensor.kennel_generic_hard_disk_load_used_space_2
          - sensor.kennel_generic_hard_disk_load_used_space

      - type: custom:apexcharts-card
        header:
            show: true
            title: Resources
            show_states: true
            colorize_states: true
        chart_type: radialBar
        series:
          - entity: sensor.kennel_intel_core_i5_4690_load_cpu_total
            name: CPU Total
            color: red
          - entity: sensor.kennel_generic_memory_load_memory
            name: Memory Load
            color: yellow

      - type: horizontal-stack
        cards:
          - type: glance
            title: HDD Temps
            columns: 3
            entities:
              - sensor.kennel_wdc_wd1003fbyz_010fb0_temperatures_temperature
              - sensor.kennel_wdc_wd120emfz_11a6ja0_temperatures_temperature
              - sensor.kennel_wdc_wd120emfz_11a6ja0_temperatures_temperature_2
              - sensor.kennel_wdc_wd120emfz_11a6ja0_temperatures_temperature_3
              - sensor.kennel_st3000vn000_1hj166_temperatures_temperature
              - sensor.kennel_st3000vn000_1hj166_temperatures_temperature_2

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.qbittorrent_down_speed
                show_points: false
            height: 200
            lower_bound: 0
            aggregate_func: max
            line_width: 10
            line_color: blue
            hours_to_show: 12
            show:
                extrema: true
                labels: true

          - type: custom:mini-graph-card
            entities:
              - entity: sensor.qbittorrent_up_speed
                show_points: false
            height: 200
            lower_bound: 0
            aggregate_func: max
            line_width: 10
            line_color: red
            hours_to_show: 12
            show:
                extrema: true
                labels: true

      - type: entities
        title: Protect Stats
        entities:
          - binary_sensor.doghousepro_disk_0_health
          - sensor.doghousepro_resolution_free_space
          - sensor.doghousepro_uptime
          - sensor.doghousepro_type_continuous_video
          - sensor.doghousepro_type_detections_video
          - sensor.doghousepro_type_timelapse_video

      - type: entities
        title: UPS Stats
        entities:
          - sensor.ups_model
          - sensor.ups_status
          - sensor.ups_input_voltage
          - sensor.ups_output_voltage
          - sensor.ups_internal_temperature
          - sensor.ups_battery
          - sensor.ups_load
          - sensor.ups_time_left

################################################################################
# Power tab
################################################################################
  - title: Power
    icon: mdi:power-socket-us
    path: power
    cards:
      - type: custom:mini-graph-card
        line_width: 5
        hours_to_show: 24
        animate: false
        show:
            fill: false
            labels: hover
            name_adaptive_color: true
        entities:
          - sensor.deskcomputer
          - sensor.livingroomtv
          - sensor.kidstv
          - sensor.consoles

      - type: entities
        entities:
          - sensor.deskcomputer
          - sensor.deskmonitor
          - sensor.deskspeakers
          - sensor.brotherprinter
          - sensor.homeassistant
          - sensor.desklamp
          - sensor.google_home_mini

      - type: entities
        entities:
          - sensor.livingroomtv
          - sensor.chromecast

      - type: entities
        entities:
          - sensor.kidstv
          - sensor.consoles
################################################################################
# Media tab
################################################################################
  - title: Media
    icon: mdi:movie-roll
    path: media
    cards:
      - type: picture-elements
        image: /local/images/plex_banner.jpg
        elements:
          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Total </b>"
            style: {left: 20%, top: 14%}
          - type: state-label
            entity: sensor.tautulli
            style: {color: white, font-size: 16px, left: 20%, top: 26%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Direct play </b>"
            style: {left: 55%, top: 14%}
          - type: state-label
            entity: sensor.tautulli_direct_plays
            style: {color: white, font-size: 16px, left: 55%, top: 26%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Direct stream </b>"
            style: {left: 20%, top: 44%}
          - type: state-label
            entity: sensor.tautulli_direct_streams
            style: {color: white, font-size: 16px, left: 20%, top: 56%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>Transcode </b>"
            style: {text-align: left,left: 55%, top: 44%}
          - type: state-label
            entity: sensor.tautulli_count_transcode
            style: {color: white, font-size: 16px, left: 55%, top: 56%}

          - type: custom:text-element
            text: "<b style='color: orange; font-size: 16px'>LAN bandwidth </b>"
            style: {left: 20%, top: 74%}
          - type: state-label
            entity: sensor.tautulli_lan_bandwidth
            style: {color: white, font-size: 16px, left: 20%, top: 86%}

          - type: custom:text-element
            text: "<b text-align: left, style='color: orange; font-size: 16px'>WAN bandwidth </b>"
            style: {left: 55%, top: 74%}
          - type: state-label
            entity: sensor.tautulli_wan_bandwidth
            style: {color: white, font-size: 16px, left: 55%, top: 86%}

      - type: entities
        title: Plex Stats
        entities:
          - sensor.plex_intel_core_i5_8500t_temperatures_cpu_package
          - sensor.plex_generic_memory_data_available_memory
          - sensor.plex_generic_memory_data_used_memory

      - type: horizontal-stack
        cards:
          - type: gauge
            name: CPU Load
            unit: '%'
            entity: sensor.plex_intel_core_i5_8500t_load_cpu_total
            severity:
                green: 0
                yellow: 45
                red: 85

          - type: gauge
            name: Memory Load
            unit: '%'
            entity: sensor.plex_generic_memory_load_memory
            severity:
                green: 0
                yellow: 45
                red: 85

      - type: conditional
        conditions:
          - entity: sensor.sonarr_upcoming
            state_not: '0'
        card:
            type: custom:upcoming-media-card
            entity: sensor.sonarr_upcoming_media
            image_style: poster
            title: Upcoming TV

      - type: conditional
        conditions:
          - entity: sensor.radarr_upcoming
            state_not: '0'
        card:
            type: custom:upcoming-media-card
            entity: sensor.radarr_upcoming_media
            image_style: poster
            title: Upcoming Movies

################################################################################
# Misc tab
################################################################################
  - title: Misc
    icon: mdi:clipboard-pulse
    path: misc
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - entity: switch.will_coffee
            name: Coffee for Will
          - entity: switch.overtime_coffee
            name: Overtime Coffee

      - type: custom:mini-graph-card
        line_width: 5
        hours_to_show: 48
        points_per_hour: 0.25
        animate: false
        show:
            fill: false
            labels: hover
            name_adaptive_color: true
        entities:
          - entity: sensor.living_room_thermostat_air_temperature
            name: Living Room
          - entity: sensor.livingroomtemp
            name: Front Door

      - type: picture-entity
        name: Weather Map
        entity: camera.weather_map
        aspect_ratio: 0%
        camera_view: live
        show_name: false
        show_state: false

      - type: entities
        title: SSL Expirations
        show_header_toggle: false
        entities:
          - sensor.cert_expiry_timestamp_bakkoda_com
          - sensor.cert_expiry_timestamp_hass_bakkoda_com
          - sensor.cert_expiry_timestamp_scarylegrunners_com

      - type: entities
        title: Update Stats
        show_header_toggle: false
        entities:
          - sensor.ansible_status
          - sensor.pihole_status

      - type: entities
        title: Veeam Stats
        show_header_toggle: false
        entities:
          - sensor.critical_backups
          - sensor.weekly_backups

      - type: entities
        title: Personal Backups
        show_header_toggle: false
        entities:
          - sensor.personal_backups
          - sensor.personal_data_ext
          - sensor.personal_pictures_ext
          - sensor.personal_users_ext

      - type: entities
        title: Server Backups
        show_header_toggle: false
        entities:
          - sensor.database_backups
          - sensor.server_backups
          - sensor.servers_data_ext
          - sensor.servers_speed_ext

      - type: entities
        title: Pi-Hole Stats
        show_header_toggle: false
        entities:
          - switch.pihole
          - sensor.pihole_domains_blocked
          - sensor.pihole_dns_queries_today
          - sensor.pihole_ads_blocked_today
          - sensor.pihole_ads_percentage_blocked_today
