sensor:
  - name: "Ansible status"
    state_topic: "homeassistant/ansible/status"

  - name: "Pihole status"
    state_topic: "homeassistant/pihole/status"

  - name: "Personal backups"
    state_topic: "homeassistant/backups/personal"

  - name: "Personal Data (Ext)"
    state_topic: "homeassistant/backups/ext_personal_data"

  - name: "Personal Pictures (Ext)"
    state_topic: "homeassistant/backups/ext_personal_pictures"

  - name: "Personal Users (Ext)"
    state_topic: "homeassistant/backups/ext_personal_users"

  - name: "Server backups"
    state_topic: "homeassistant/backups/servers"

  - name: "Servers Speed (Ext)"
    state_topic: "homeassistant/backups/ext_server_speed"

  - name: "Servers Data (Ext)"
    state_topic: "homeassistant/backups/ext_server_data"

  - name: "Critical backups"
    state_topic: "homeassistant/backups/critical"

  - name: "Weekly backups"
    state_topic: "homeassistant/backups/weekly"

  - name: "Database backups"
    state_topic: "homeassistant/backups/databases"